version: "3.8"

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8888"
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8888:8888"

  db:
    image: postgres:12.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hackaton
    ports:
      - '5440:5432'
    restart: always


volumes:
  postgres_data:
