MAPPED_APARTMENT_FIELDS = {
    'statusMkd': 'col_3163',
    'floor_count': 'col_759',
    'year': 'col_756',
    'total_area': 'col_762',
    'project_series': 'col_758',
    'materialWall': 'col_769',
    'count_passenger_elevators': 'col_771',
    'count_cargo_passenger_elevators': 'col_772',
    'total_area_of_residential_premises': 'col_763',
    'total_area_of_non_residential_premises': 'col_764',
    'number_of_entrances': 'col_760',
    'number_of_freight_elevators': 'col_3363',
    'type_of_housing_stock': 'col_2463',
    'a_sign_of_a_building_accident': 'col_770',
    'apartments_number': 'col_761',
    'materialRoof': 'col_781',
    'mcd_management_status': 'col_3243',
    'appointment': 'col_754',
    'the_order_of_roof_cleaning': 'col_775',
    'construction_volume': 'col_765',
    'object_wear_and_tear': 'col_103506',
    'reason_change_status': 'col_3468',
    'parent_id': 'parent_id',
    'year_reconstruction': 'col_757',
    'social_object_type': 'col_2156',
    'ownership_form': 'col_755',
    'energy_efficiency_class': 'col_767'
}

